image:
  file: Dockerfile

tasks:
  - init: |
      mysql -e "CREATE USER 'monUser'@'localhost' IDENTIFIED BY 'monPassword';"
      mysql -e "CREATE DATABASE GestionPedaBD"
      mysql -e "GRANT ALL PRIVILEGES ON GestionPedaBD.* TO 'monUser'@'localhost';"
      mysql -u monUser -pmonPassword GestionPedaBD < gestion_peda_mysql.sql
      mvn verify -DskipTests=true 
  - command: mvn compile exec:java -Dexec.mainClass=fr.univ_amu.iut.ExempleJDBC -Dexec.cleanupDaemonThreads=false -DskipTests=true 

ports:
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-java-pack
    - redhat.vscode-commons
    - redhat.java
    - redhat.vscode-xml
    - redhat.fabric8-analytics

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
